const model = require('../middleware/controllers/model')

let data = [
    { b: 1 },
    { b: 2 },
    { a: 'string' },
    { a: true },
    { a: 5 },
    { a: 6 },
    { a: 7 },
    { a: 8 },
    { a: 9 },
    { a: 10 },
    { a: 11 },
    { a: 12 },
    { a: 13 },
    { a: 14 },
    { a: 15 },
    { a: 16 },
    { a: 17 },
    { a: 18 },
    { a: 19 },
    { a: 20 },
    { a: 21 },
    { a: 22 },
    { a: 23 },
    { a: 24 },
    { a: 25 },
    { a: 1 },
    { a: 2 },
    { a: 3 },
    { a: 4 },
    { a: 5 },
    { a: 6 },
    { a: 7 },
    { a: 8 },
    { a: 9 },
    { a: 10 },
    { a: 11 },
    { a: 12 },
    { a: 13 },
    { a: 14 },
    { a: 15 },
    { a: 16 },
    { a: 17 },
    { a: 18 },
    { a: 19 },
    { a: 20 },
    { a: 21 },
    { a: 22 },
    { a: 23 },
    { a: 2 },
    { a: 3 },
    { a: 4 },
    { a: 5 },
    { a: 6 },
    { a: 7 },
    { a: 8 },
    { a: 9 },
    { a: 10 },
    { a: 11 },
    { a: 12 },
    { a: 13 },
    { a: 14 },
    { a: 15 },
    { a: 16 },
    { a: 17 },
    { a: 18 },
    { a: 19 },
    { a: 20 },
    { a: 21 },
    { a: 22 },
    { a: 23 },
    { a: 24 },
    { a: 25 },
    { a: 1 },
    { a: 2 },
    { a: 3 },
    { a: 4 },
    { a: 5 }
]

let template = {
    name: 'ex',
    required: ['a'],
    enforceType: ['a'],
    default: [{ key: 'timestamp', formula: 'new Date().getTime()' }, { key: 'b.c', formula: 'data.a*100' }],
    model: {
        a: 1
    }
}

if (Array.isArray(data) && data.length) {
    model.validate(data, template)
        .then(result => console.log(result))
        .catch(e => console.log(e))
}
